name: Create Tag and Release

on:
  push:
    branches:
      - main

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Get version from pubspec.yaml
      id: get_version
      run: |
        VERSION=$(grep 'version: ' pubspec.yaml | sed 's/version: //')
        echo "PACKAGE_VERSION=${VERSION}" >> $GITHUB_ENV
        echo "::set-output name=version::${VERSION}"

    - name: Create and Push tag
      run: |
        git tag v${{ steps.get_version.outputs.version }}
        git push origin v${{ steps.get_version.outputs.version }}
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        release_name: Release v${{ steps.get_version.outputs.version }}
        body: |
          Release v${{ steps.get_version.outputs.version }} of Flongo-Client :tada:

          [View on pub.dev](https://pub.dev/packages/flongo_client/versions/${{ steps.get_version.outputs.version }})
          
