name: Create Tag and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for the tag (e.g., 1.0.0)'
        required: true

jobs:
  tag-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Create and Push tag
      run: |
        git tag v${{ github.event.inputs.version }}
        git push origin v${{ github.event.inputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      with:
        tag_name: v${{ github.event.inputs.version }}
        release_name: Release v${{ github.event.inputs.version }}
        body: |
          Release v${{ github.event.inputs.version }} of Flongo-Client :tada:

          [View on pub.dev](https://pub.dev/packages/flongo_client/versions/v${{ github.event.inputs.version }})
